### PR TITLE
Create PR-3

### PR DESCRIPTION
**Pull request by jltng**
## Changes

Assignment: added name to README file

## Checklist

- [x] Pull request has descriptive context useful to reviewer. Screenshots are attached as necessary.
- [x] Pull request title matches Jira ticket.
- [x] Ticket has been claimed on Jira
- [x] Pull request has been approved by CodeOwner

### CODE REVIEW

**Comment by jltng** [comment]
lol wait don't think this worked out

**Comment by gin-guo** [comment]
It looks like you made a change to the gitignore file instead of README.md. Try finding the "Contributors" section shown below.
image
Great work for creating the pull request though!

**Comment by Jnwong116** [comment]
Great comment @gin-guo! Yea both of you made changes to the .gitignore. You should be updating the README.md

Next time @gin-guo  you can also try the request changes feature.

**Review by Jnwong116 — CHANGES_REQUESTED** [review]
@jltng Please run this command `git reset --hard HEAD^` in your terminal before going any further. 

You accidentally deleted the .gitignore so if we merge your change it will delete the .gitignore from the repo which is not what we want to do. Instead by doing git reset --hard HEAD^ you will effectively revert all your changes made. 

You can then go and edit the README afterwards and it will be as if you only changed the README and didn't delete or edit the .gitignore

**Review by Jnwong116 — APPROVED** [review]
Good job. You will have merge conflicts though!

**Review by Jnwong116 — COMMENTED** [review]
Next to each persons' name on the README you should add a `<br />`

**Review by kelvincklo — APPROVED** [review]

**Pull request merged**
