### PR TITLE
CCF-16 Create PR-6

### PR DESCRIPTION
**Pull request by latexsupremecist**
## Changes

Added my name "Daniel Chua" to README.md

## Checklist

- [x] Pull request has descriptive context useful to reviewer. Screenshots are attached as necessary.
- [x] Pull request title matches Jira ticket.
- [x] Ticket has been claimed on Jira
- [x] Pull Request has been assigned to yourself
- [x] Pull request has been approved by CodeOwner
- [x] Pull request has been approved by one other student

### CODE REVIEW

**Comment by Jnwong116** [comment]
What is this DS_store file that you added? Also in the future, you should assign Chris as a reviewer and not as an assignee.

**Comment by latexsupremecist** [comment]
Apparently it’s an Apple problem (https://en.wikipedia.org/wiki/.DS_Store). It stores custom attributes of its containing folder, but doesn’t really do anything. I’ve added to my ~/.gitignore_global. Is there a way to restore the branch so it’s ignored in my commits?

**Comment by Jnwong116** [comment]
@latexsupremecist yea you can do git restore <file name> to remove it from the commit.

**Comment by latexsupremecist** [comment]
Deleted .DS_Store and updated the list in README.md

**Review by Jnwong116 — APPROVED** [review]
Fix your merge conflicts but otherwise should be good!

**Review by chrisouy4ng — APPROVED** [review]
Very good. I approve

**Pull request merged**
